[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:portal]
command=gunicorn --worker-class gevent --workers 1 --bind 0.0.0.0:7002 --timeout 120 app:app
directory=/app/portal
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:scraper]
command=gunicorn --worker-class gevent --workers 1 --bind 0.0.0.0:5050 --timeout 120 dashboard.app:app
directory=/app/scraper
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:miravia]
command=gunicorn --worker-class gevent --workers 1 --bind 0.0.0.0:7000 --timeout 120 app:app
directory=/app/shopify-miravia-sync
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -c /tmp/nginx.conf -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
